spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true



camunda.bpm.admin-user:
  id: root
  password: root
camunda.bpm:
  deployment-resource-pattern:
    - "*.bpmn"
    - "*.dmn"
    - "*.form"